apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  labels:
    app: demo
    tier: frontend
spec:
  ports:
  - port: 9999
    targetPort: 9080
    nodePort: 31999
  selector:
    app: demo
    tier: frontend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
        tier: frontend
    spec:
      containers:
      - name: master
        image: liberty_demo:demo
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9080
