apiVersion: v1
entries:
  libertysimple:
  - created: 2018-03-13T12:51:55.122746+01:00
    description: Simple Liberty Demo
    digest: 576f1be38870bcba3e14078e9abe8f2cedf5364cf66fa90c6120f01ba180302a
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/libertysimple/raw/master/charts/stable/icons/liberty.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: libertysimple
    sources:
    - https://github.com/niklaushirt/libertysimple
    urls:
    - https://raw.githubusercontent.com/niklaushirt/libertysimple/master/charts/stable/repo/stable/libertysimple-1.1.0.tgz
    version: 1.1.0
  - created: 2018-03-13T12:51:55.122452+01:00
    description: Simple Liberty Demo
    digest: c71d06df443ec83ce30df3785a0ca892286fdf997073cef0f1c480cb144f9f4a
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/libertysimple/raw/master/charts/stable/icons/liberty.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: libertysimple
    sources:
    - https://github.com/niklaushirt/libertysimple
    urls:
    - https://raw.githubusercontent.com/niklaushirt/libertysimple/master/charts/stable/repo/stable/libertysimple-1.0.0.tgz
    version: 1.0.0
generated: 2018-03-13T12:51:55.12185+01:00
