apiVersion: v1
entries:
  libertysimple:
  - created: 2018-06-12T08:12:30.369816+02:00
    description: Simple Liberty Demo
    digest: 3d9093fa04af8841279b8496f311a6cf86ad6825b5b15d3f440dc898071cc62b
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/libertysimple/raw/master/charts/stable/icons/liberty.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: libertysimple
    sources:
    - https://github.com/niklaushirt/libertysimple
    urls:
    - https://raw.githubusercontent.com/niklaushirt/libertysimple/master/charts/stable/repo/stable/libertysimple-1.3.0.tgz
    version: 1.3.0
  - created: 2018-06-12T08:12:30.3695+02:00
    description: Simple Liberty Demo
    digest: 5cff53d731dd3b29072435d68baefb26a204f8ae7634ee769c5bed48d5e1e913
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/libertysimple/raw/master/charts/stable/icons/liberty.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: libertysimple
    sources:
    - https://github.com/niklaushirt/libertysimple
    urls:
    - https://raw.githubusercontent.com/niklaushirt/libertysimple/master/charts/stable/repo/stable/libertysimple-1.2.0.tgz
    version: 1.2.0
  - created: 2018-06-12T08:12:30.368848+02:00
    description: Simple Liberty Demo
    digest: 6f3bda6d52e329fc0845f72e7ddd7b2e6ad1645dbe96b244500a1bf7c729e6e9
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/libertysimple/raw/master/charts/stable/icons/liberty.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: libertysimple
    sources:
    - https://github.com/niklaushirt/libertysimple
    urls:
    - https://raw.githubusercontent.com/niklaushirt/libertysimple/master/charts/stable/repo/stable/libertysimple-1.1.0.tgz
    version: 1.1.0
  - created: 2018-06-12T08:12:30.368299+02:00
    description: Simple Liberty Demo
    digest: 903abe5c89677706a30e77cdefd527f272acff73e0c4c4ddaa3672393307d2bb
    home: https://github.com/kubernetes/helm
    icon: https://github.com/niklaushirt/libertysimple/raw/master/charts/stable/icons/liberty.png
    keywords:
    - http
    - nginx
    - www
    - web
    maintainers:
    - email: nikh@ch.ibm.com
      name: Niklaus Hirt
    name: libertysimple
    sources:
    - https://github.com/niklaushirt/libertysimple
    urls:
    - https://raw.githubusercontent.com/niklaushirt/libertysimple/master/charts/stable/repo/stable/libertysimple-1.0.0.tgz
    version: 1.0.0
generated: 2018-06-12T08:12:30.367126+02:00
